### ISSUE TITLE
Namngivning för servrar

### ISSUE THREAD

**Issue by viirre** [adaptivemedia/guidelines.adaptivemedia.se#5]
## Nuvarande

- workfox-web-dev
- workfox-db-dev
- workfox-web-prod
- workfox-db-prod

## Förslag

- workfox-dev-web
- workfox-dev-db
- workfox-prod-web
- workfox-prod-db

Anledningen är att ordningen blir mer logisk för t.ex. listor.

Nackdelen är att vi har en del servrar som är namngivna efter det gamla sättet (t.ex. Exim).

Åsikter?

**Comment by viirre** [comment]
@sebek @TobiasFroberg @MartinCamen @jandreasn

**Comment by jandreasn** [comment]
Lättare att jämföra med båda förslagen i bokstavsordning :)

- workfox-db-dev
- workfox-db-prod
- workfox-web-dev
- workfox-web-prod

vs

- workfox-dev-db
- workfox-dev-web
- workfox-prod-db
- workfox-prod-web

**Comment by TobiasFroberg** [comment]
Kan man döpa om exim? Gillar det oavsett 👍

**Comment by viirre** [comment]
Ska kolla ok det är möjligt

**Comment by viirre** [comment]
Man kan byta hostname på servern i Glesys samt uppdatera serverns namn i Forge, så jag tror att det är doable!
